export const dessertsData = [
  {
    id: 1,
    type: "Wafle",
    title: "Waffle with Berries",
    price: 6.5,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 2,
    title: "Vanilla Bean Crème Brûlée",
    type: "Crème Brûlée",
    price: 7.0,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 3,
    title: "Macaron Mix of Five",
    type: "Macaron",
    price: 8.0,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 4,
    title: "Classic Tiramisu",
    type: "Tiramisu",
    price: 5.5,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 5,
    type: "Baklava",
    title: "Pistachio Baklava",
    price: 4.0,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 6,
    type: "Pie",
    title: "Lemon Meringue Pie",
    price: 5.0,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 7,
    type: "Cake",
    title: "Red Velvet Cake",
    price: 4.5,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 8,
    type: "Wafle",
    title: "Waffle with Berries",
    price: 6.5,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 9,
    type: "Brownie",
    title: "Salted Caramel Brownie",
    price: 4.5,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
  {
    id: 10,
    type: "Panna Cotta",
    title: "Vanilla Panna Cotta",
    price: 6.5,
    pictures: {
      desktop: "./assets/images/image-waffle-desktop.jpg",
      mobile: "./assets/images/image-waffle-mobile.jpg",
      tablet: "./assets/images/image-waffle-tablet.jpg",
      thumbnail: "./assets/images/image-waffle-thumbnail.jpg",
    },
    quantity: 0,
  },
];
